### PR TITLE
Fix #434 add static provisioner for eth1

### LINKED ISSUE #434: f36 private network not setup
ip addr doesn't show the network. I can help debug.

### PR DESCRIPTION
**Pull request by robnagler**
Fix README.md so works without index.sh and on mac

### CODE REVIEW

**Review by e-carlin — CHANGES_REQUESTED** [review]
This didn't work for me on my Mac

Shell 1:
```
$ cd ~/src/radiasoft/download
$ git checkoout 434-eth1-provision
$ cd ~/src
rm -f index.html
ln -s radiasoft/download/bin/index.sh index.html
python3 -m http.server 2916
```

shell 2:
```
$ mkdir ~/v2
$ cd $_
$ radia_run vagrant-dev fedora
<snip>
==> default: Running provisioner: shell...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: sed -i '/127.0.*v2.radia.run/d' /etc/hosts: No such file or directory
    default: Connection 'eth1' (d6e5f838-431d-40ea-ad8d-803e24f8194d) successfully added.
    default: Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 2916 after 13 ms: Connection refused
```

**Comment by robnagler** [comment]
That's why I wrote:
>  NOTE: You may have to set the IP manually for complex installers

Try the previous code, and you'll see it was worse.

vagrant-dev tries to curl from inside an ssh to the vm, which is the failure above. There's no way to get a routable address (easily) from the mac.

**Comment by e-carlin** [comment]
Ok, I switched to a linux host

```
v2$ radia_run vagrant-dev fedora
Log: /home/ecarlin/v2/radia-run-install.log
curl -L -s -S http://10.1.2.7:2916/radiasoft/download/installers/vagrant-dev/radiasoft-download.sh
Source: /var/tmp/radia-run-43165-10667/20230317223854-radiasoft-download.sh
Checking for updates to 'fedora/36-cloud-base'
Latest installed version: 36-20220504.1
Version constraints: > 36-20220504.1
Provider: virtualbox
Box 'fedora/36-cloud-base' (v36-20220504.1) is running the latest version.
/var/tmp/radia-run-43165-10667/20230317223854-radiasoft-download.sh: line 380: vagrant_dev_provision_eth1: unbound variable
2023-03-17T22:38:54Z install_main
Unexpected error; Install failed.
```

**Comment by robnagler** [comment]
Different code path. I committed a change.

**Comment by e-carlin** [comment]
Now seeing

```
==> default: Running provisioner: shell...
    default: Running: inline script
    default: /tmp/vagrant-shell: line 1: sed -i '/127.0.*v2.radia.run/d' /etc/hosts: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
2023-03-17T23:19:43Z install_main
```

**Comment by e-carlin** [comment]
Works well. That's a nice addition.

**Review by e-carlin — APPROVED** [review]

**Pull request merged**
